service: filterSvc

provider:
  name: aws
  runtime: nodejs14.x

functions:
  dispatcher:
    handler: handler.handle
    layers:
      - { Ref: FiltersLambdaLayer}
    events:
      - sns:
          arn: !Ref SampleTopic
          topicName: FilterMe

layers:
  Filters:
    path: layer
    compatibleRuntimes:
      - nodejs14.x
      - nodejs12.x
      - nodejs10.x

resources:
  Resources:
    SampleTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: FilterMe